-- Live so a new value cannot fall outside the filter. No `VAL <> ''`:
-- in Exasol the empty string IS NULL, which would blank every dropdown.
SELECT DIM, VAL FROM (
SELECT DISTINCT 'PRODUCT_NAME' AS DIM, TO_CHAR(g."PRODUCT_NAME") AS VAL FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'CATEGORY', TO_CHAR(g."CATEGORY") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'STORE_NAME', TO_CHAR(g."STORE_NAME") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'ORDER_STATUS', TO_CHAR(g."ORDER_STATUS") FROM "RETAIL"."ORDERS_ENRICHED" g
) WHERE VAL IS NOT NULL ORDER BY DIM, VAL LIMIT 500
