-- Live so a new value cannot fall outside the filter. No `VAL <> ''`:
-- in Exasol the empty string IS NULL, which would blank every dropdown.
SELECT DIM, VAL FROM (
SELECT DISTINCT 'CATEGORY' AS DIM, TO_CHAR(g."CATEGORY") AS VAL FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'SUBCATEGORY', TO_CHAR(g."SUBCATEGORY") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'PRODUCT_NAME', TO_CHAR(g."PRODUCT_NAME") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'CHANNEL', TO_CHAR(g."CHANNEL") FROM "RETAIL"."ORDERS_ENRICHED" g
) WHERE VAL IS NOT NULL ORDER BY DIM, VAL LIMIT 500
