-- Live so a new value cannot fall outside the filter. No `VAL <> ''`:
-- in Exasol the empty string IS NULL, which would blank every dropdown.
SELECT DIM, VAL FROM (
SELECT DISTINCT 'ORDER_STATUS' AS DIM, TO_CHAR(g."ORDER_STATUS") AS VAL FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'CATEGORY', TO_CHAR(g."CATEGORY") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'STORE_NAME', TO_CHAR(g."STORE_NAME") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'PAYMENT_METHOD', TO_CHAR(g."PAYMENT_METHOD") FROM "RETAIL"."ORDERS_ENRICHED" g
) WHERE VAL IS NOT NULL ORDER BY DIM, VAL LIMIT 500
