-- Live so a new value cannot fall outside the filter. No `VAL <> ''`:
-- in Exasol the empty string IS NULL, which would blank every dropdown.
SELECT DIM, VAL FROM (
SELECT DISTINCT 'CUSTOMER_SEGMENT' AS DIM, TO_CHAR(g."CUSTOMER_SEGMENT") AS VAL FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'AGE_BAND', TO_CHAR(g."AGE_BAND") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'CUSTOMER_CITY', TO_CHAR(g."CUSTOMER_CITY") FROM "RETAIL"."ORDERS_ENRICHED" g
  UNION ALL SELECT DISTINCT 'FAV_CATEGORY', TO_CHAR(g."FAV_CATEGORY") FROM "RETAIL"."ORDERS_ENRICHED" g
) WHERE VAL IS NOT NULL ORDER BY DIM, VAL LIMIT 500
